version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install

  pre_build:
    commands:
      - npm run lint:fix
      - echo "Running linter"
      - npm run lint:all
      - echo "Running tests"
      - npm run test
      - echo "List the contents of the coverage directory"
      - ls -la coverage/
      - echo "Building the application"
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Coverage directory path:"
      - echo $(pwd)/coverage
      
reports:
  CoberturaReportGroup:
    files:
      - 'coverage/cobertura-coverage.xml'
    file-format: COBERTURAXML
    base-directory: '/codebuild/output/src*/src/'
    export-config:
      export-to: S3
      s3-bucket: 'codepipeline-us-east-1-689541132237'
      s3-key-prefix: reports/

artifacts:
  files:
    - dist/**/*
  discard-paths: yes
