version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - npm install --verbose
  pre_build:
    commands:
      - npm run lint:fix
      - npm run lint:all
      - npm run test
      - npm run format:check
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
