version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install

  pre_build:
    commands:
      - npm run lint:fix
      - echo "Running linter"
      - npm run lint:all
      - echo "Running tests"
      - npm run test
      - echo "Building the application"
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"
      
reports:
  CoberturaReportGroup:
    files:
      - 'coverage/cobertura-coverage.xml'
    file-format: COBERTURAXML
    base-directory: 'coverage/'

artifacts:
  files:
    - dist/**/*
  discard-paths: yes
