version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run lint:all
      - npm run test
      - npm run format:check
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
